apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-grpc-deployment-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-grpc-b
  template:
    metadata:
      labels:
        app: mt-grpc-b
      # annotations:
      #   sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: test-grpc-b
          image: mayanktripathi21/test-grpc-b:0.6
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-grpc-deployment-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-grpc-c
  template:
    metadata:
      labels:
        app: mt-grpc-c
      # annotations:
      #   sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: test-grpc-c
          image: mayanktripathi21/test-grpc-b:0.6
          ports:
            - containerPort: 8080

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-grpc-deployment-a-insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-grpc-a-insecure
  template:
    metadata:
      labels:
        app: mt-grpc-a-insecure
      # annotations:
      #   sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: test-grpc-c
          image: mayanktripathi21/test-grpc-a:0.6
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-grpc-deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-grpc-a
  template:
    metadata:
      labels:
        app: mt-grpc-a
      # annotations:
      #   sidecar.istio.io/inject: 'true'
    spec:
      volumes:
        - name: ingress-w-ssl-storage-dev-cert
          secret:
            secretName: ingress-mt-test-grpc-cert
            defaultMode: 420
      containers:
        - name: test-grpc-a
          image: mayanktripathi21/test-grpc-a:0.10
          volumeMounts:
            - name: ingress-w-ssl-storage-dev-cert
              mountPath: /usr/src/app/certs
          ports:
            - containerPort: 8080