apiVersion: v1
kind: Service
metadata:
  name: test-grpc-a
spec:
  selector:
    app: mt-grpc-a
  ports:
  - port: 80
    name: grpc
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: test-grpc-a-insecure
spec:
  selector:
    app: mt-grpc-a-insecure
  ports:
  - port: 80
    name: grpc
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: test-grpc-b
spec:
  selector:
    app: mt-grpc-b
  ports:
  - port: 80
    name: grpc
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: test-grpc-c
spec:
  selector:
    app: mt-grpc-c
  ports:
  - port: 80
    name: grpc
    targetPort: 8080