FROM node:14

ENV PORT=8080
ENV SERVICEAURI="test-grpc-a"
ENV SERVICEBURI="test-grpc-b"
ENV SERVICECURI="test-grpc-c"

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080
CMD [ "node", "server-a.js" ]